[package]
name = "oauth2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.1"

[dependencies.curl]
git = "https://github.com/carllerche/curl-rust.git"

[dependencies.url]
git = "https://github.com/servo/rust-url"
